## **TUGAS KELIMA**
(03 April 2023)



ini merupakan perbaikan tugas kelima, karena adanya ketidakselesaian materi pada numpy di tugas kelima sebelumnya.

# **5.16 List 2 Dimensi**

List 2 dimensi umumnya menempatkan sebuah list di dalam list.

Penggambarannya seperti matrik

In [126]:
#LATIHAN 1
#akan mencoba  membuat list dalam bentuk angka random

#kita bebas membuat list dengan bilangan apa saja
matrik = [
    [25, 37, 46, 59, 62, 71],
    [22, 15, 29, 55, 90, 31],
    [11, 67, 23, 87, 47, 25],
    [77, 89, 25, 38, 48, 90],
    ]
#harus menggunakan kurung siku di awal dan di akhir, karena jika tidak memakai maka akan error
#pada akhir setiap baris juga harus menggunakan koma, karena meskipun satu koma saja tidak ditulis maka sudah pasti akan error 
#perlu diingat bahwa,list ditulis sebagai daftar nilai yang dipisahkan koma antara tanda kurung siku

print(matrik)
#print matrik agar dapat terbaca keseluruhan matrik saat di run


[[25, 37, 46, 59, 62, 71], [22, 15, 29, 55, 90, 31], [11, 67, 23, 87, 47, 25], [77, 89, 25, 38, 48, 90]]


In [127]:
matrik [0]
#masih menggunakan list yang sama seperti di atas, jadi tidak perlu ditulis ulang
#perlu diingat bahwa python bermula dari 0, jadi matrik baris paling atas adalah matrik 0


[25, 37, 46, 59, 62, 71]

In [128]:
matrik [-2]
#urutan baris matrik nomor 2 dari belakang (ini berarti sama dengan baris ke 3

[11, 67, 23, 87, 47, 25]

In [129]:
matrik [1][2] = 150 
#ini berarti, angka pada baris ke 1 dengan kolom ke 2 akan diganti oleh angka 150
print (matrik[1][2])
#harus diberi print karena kalau tidak diberi, tidak menampilkan apapun

150


In [130]:
#setelah angkanya diganti, coba kita akan menampilkan ulang matrik yang telah dibuat di atas
matrik
#terbukti bahwa angka pada baris ke 1 dengan kolom 2 angkanya berubah menjadi 150

[[25, 37, 46, 59, 62, 71],
 [22, 15, 150, 55, 90, 31],
 [11, 67, 23, 87, 47, 25],
 [77, 89, 25, 38, 48, 90]]

In [131]:
#coba memanggil anggota atau elemen baris dan kolom dari matrik di atas

for baris in matrik:      #akan menampilkan baris pada matrik di atas
  print (baris)           #gunakan perintah print untuk menampilkan baris
  for kolom in baris:     #akan menampilkan kolom pada baris di atas
    print (kolom)         #gunakan perintah print untuk menampilkan kolom

#karena ini merupakan list maka yang ditampilkan adalah perubahan pada matrik yang dilakukan terakhir kali

[25, 37, 46, 59, 62, 71]
25
37
46
59
62
71
[22, 15, 150, 55, 90, 31]
22
15
150
55
90
31
[11, 67, 23, 87, 47, 25]
11
67
23
87
47
25
[77, 89, 25, 38, 48, 90]
77
89
25
38
48
90


In [132]:
#LATIHAN 2
#saya akan mencoba membuat list dua dimensi dengan jumlah elemen yang berbeda

#langkah yang pertama, saya akan membuat dengan angka random
matrik = [
    [2, 6, 8, 10, 15, 12],      #baris pertama terdapat 6 elemen
    [3, 6, 9, 4],               #baris kedua terdapat 4 elemen
    [2, 7, 16],                 #baris ketiga terdapat 3 elemen
    [5, 11, 14, 17, 20],        #baris keempat terdapat 5 elemen
]
#pada contoh di atas terlihat bahwa list dua dimensi memiliki jumlah yang berbeda tiap barisnya
print (matrik)

[[2, 6, 8, 10, 15, 12], [3, 6, 9, 4], [2, 7, 16], [5, 11, 14, 17, 20]]


In [133]:
#kita akan lihat apakah list dua dimensi bisa mengoprasikan apabila jumlah elemen berbeda tiap barisnya

matrik [2]
#menampilkan baris ke 2

[2, 7, 16]

In [134]:
matrik [0][2]
#menampilkan baris ke 0 kolom ke 2

8

In [135]:
matrik [1][0] = 50
print (matrik [1][0])
#ini artinya, mengubah elemen yang ada di baris 1 kolom 0 dengan angka 50
#akan dibuktikan apakah elemen baris 1 kolom 0dapat mengubah angka menjadi 50

50


In [136]:
matrik
#terbukti bahwa elemen baris 1 kolom 0 berubah menjadi 50

[[2, 6, 8, 10, 15, 12], [50, 6, 9, 4], [2, 7, 16], [5, 11, 14, 17, 20]]

In [137]:
#cara memanggil elemen atau anggota dari matrik di atas

for baris in matrik:      #akan menampilkan baris pada matrik di atas
  print (baris)           #gunakan perintah print untuk menampilkan baris
  for kolom in baris:     #akan menampilkan kolom pada baris di atas
    print (kolom)         #gunakan perintah print untuk menampilkan kolom

#karena ini merupakan list maka yang ditampilkan adalah perubahan pada matrik yang dilakukan terakhir 

[2, 6, 8, 10, 15, 12]
2
6
8
10
15
12
[50, 6, 9, 4]
50
6
9
4
[2, 7, 16]
2
7
16
[5, 11, 14, 17, 20]
5
11
14
17
20


Kesimpulan:

List memiliki keistimewaan dimana kita bebas mendefinisikan atau membuat berapa elemen dari setiap baris.
Hal ini tentunya akan memudahkan kita saat membuat program yang lebih kompleks.

In [138]:
#kita akan membuat list barang apa saja yang ada di toko diska

barang = [
    ['baju', 'tas', 'boneka'],
    ['sepatu', 'topi', 'sarung'],
    ['celana', 'rok', 'peci'],
    ['sandal', 'kacamata', 'kerudung'],
    ['jaket', 'masker', 'sajadah'],
    ['daster', 'gamis', 'tasbih'],
]
#jangan lupa untuk menambahkan '' pada sebelum dan setelah menulis list, karena akan eror apabila tidak ditambah ''
#akan menampilkan elemen dari keseluruhan barang
print (barang)

[['baju', 'tas', 'boneka'], ['sepatu', 'topi', 'sarung'], ['celana', 'rok', 'peci'], ['sandal', 'kacamata', 'kerudung'], ['jaket', 'masker', 'sajadah'], ['daster', 'gamis', 'tasbih']]


In [139]:
#mencoba memanggil/menampilkan beberapa elemen dari barang
#gunakan perintah print untuk menampilkan hasil
#barang tidak perlu ditulis lagi karena ini merupakan lanjutan
print (barang[0])
#maksudnya adalah menampilkan elemen pada baris ke 0 yang ada di barang

['baju', 'tas', 'boneka']


In [140]:
print (barang[-1])
#menampilkan elemen pada baris ke 1 dari belakang

['daster', 'gamis', 'tasbih']


In [141]:
print (barang[2][0])
#menampilkan elemen pada baris ke 2 kolom ke 0

celana


In [142]:
print (barang)
#tetap tidak merubah list yang telah dibuat di awal tadi

[['baju', 'tas', 'boneka'], ['sepatu', 'topi', 'sarung'], ['celana', 'rok', 'peci'], ['sandal', 'kacamata', 'kerudung'], ['jaket', 'masker', 'sajadah'], ['daster', 'gamis', 'tasbih']]


In [143]:
#saya akan memanggil elemen barang

for baris in barang:      #akan menampilkan baris pada barang di atas
  print (baris)           #gunakan perintah print untuk menampilkan baris
  for kolom in baris:     #akan menampilkan kolom pada baris di atas
    print (kolom)         #gunakan perintah print untuk menampilkan kolom

#karena ini merupakan list maka yang ditampilkan adalah perubahan pada barang yang dilakukan terakhir 

['baju', 'tas', 'boneka']
baju
tas
boneka
['sepatu', 'topi', 'sarung']
sepatu
topi
sarung
['celana', 'rok', 'peci']
celana
rok
peci
['sandal', 'kacamata', 'kerudung']
sandal
kacamata
kerudung
['jaket', 'masker', 'sajadah']
jaket
masker
sajadah
['daster', 'gamis', 'tasbih']
daster
gamis
tasbih


# **5.17 Tuples**

Tuples sebenarnya mirip dengan list, akan tetapi yang membedakannya adalah tuples tidak dapat dirubah isinya.

In [144]:
#LATIHAN 1
#saya akan menampilkan beberapa fakultas yang ada di universitas udayana

fakultas = ('mipa', 'kedokteran', 'teknik', 'hukum', 'pariwisata', 'peternakan')
#tuples diawali dan ditutup dengan tanda kurung buka dan memisahkan setiap elemen di dalamnya dengan menggunakan koma
#apabila tidak menggunakan tanda kurung buka dan koma, maka akan error
print (fakultas)
#menggunakan perintah print agar fakultas dapat ditampilkan

('mipa', 'kedokteran', 'teknik', 'hukum', 'pariwisata', 'peternakan')


In [145]:
print (fakultas[5])
#menampilkan elemen di urutan ke 5

peternakan


In [146]:
print (fakultas[1:3])
#ini maksudnya menampilkan elemen dari urutan ke 1 hingga ke urutan ke 2, urutan ke 3 tidak ikut


('kedokteran', 'teknik')


In [147]:
#saya akan mencoba membuat perubahan pada elemen fakultas

fakultas[5] = ('pertanian')     #ini artinya, urutan ke 5 akan diubah menjadi pertanian
#error karena tuple tidak dapat dirubah isinya/elemennya

TypeError: ignored

In [148]:
fakultas.remove('teknik')        #remove artinya kita akan menghapus elemen teknik
#ini error karena tuple tidak dapat dirubah isinya/elemennya


AttributeError: ignored

In [149]:
fakultas.append('kedokteran_gigi')   #append berguna untuk menambahkan objek ke list
#error karena elemen tuple tidak dapat diubah, diganti, maupun ditambahkan

AttributeError: ignored

In [150]:
fakultas.upper('peternakan')     #upper maksudnya memperbesar huruf pada elemen peternakan
#error karena isi/elemen tuple tidak dapat diubah

AttributeError: ignored

In [151]:
fakultas.count('ilmu_budaya')     #ini maksudnya menghitung ada berapa elemen ilmu budaya di fakultas
#oleh karena itu, ilmu budaya di fakultas adalah 0, karena ilmu budaya bukan elemen

0

In [152]:
fakultas.count('mipa')       #ini maksudnya menghitung ada berapa elemen mipa di fakultas
#oleh karena itu, elemen mipa di fakultas hanya ada satu

1

In [153]:
#mencari panjang dari fakultas
len(fakultas) 
#maka diperoleh panjang dari fakultas adalah 6

6

In [154]:
#coba memanggil semua elemen pada fakultas 

for i in fakultas:
  print (i)

mipa
kedokteran
teknik
hukum
pariwisata
peternakan


In [155]:
#LATIHAN 2
#saya akan membuat tuple dengan elemen bilangan ganjil

#tulis elemen-elemen ganjil
ganjil = (1, 3, 5, 7, 9, 11, 13, 15, 17, 19)
print (ganjil)
#gunakan perintah print agar ditampilkan

(1, 3, 5, 7, 9, 11, 13, 15, 17, 19)


In [156]:
#menentukan nilai maksimum
#nilai maksimum adalah nilai ganjil pada urutan paling belakang
#maka diperoleh hasilnya 19
max (ganjil)

19

In [157]:
#menentukan nilai minimum
#nilai minimum adalah nilai ganjil pada urutan paling depan
#maka diperoleh hasilnya 1
min (ganjil)

1

In [158]:
#menentukan jumlah
#jumlah yang ditentukan adalah jumlah dari elemen ganjil
sum (ganjil)

100

In [159]:
#menampilkan elemen ganjil urutan ke print 1 sampai 5
#dengan 1 kurang dari 5
#artinya, 1 dan 5 tidak tergolong / tiak ikut
(ganjil[1:5])

(3, 5, 7, 9)

In [160]:
#menampilkan elemen ganjil pada urutan ke 10
#sudah pasti tidak ada, karena itu hasilnya error
print (ganjil[10])

IndexError: ignored

In [ ]:
#coba tampikan tuple sekarang

for bilangan in ganjil:
  print (bilangan)
  #menggunakan perintah print agar dapat ditampilkan
#elemen tetap dan tidak ada yang berubah maupun bertambah
#elemen ditampilkan dalam bentuk vertikal

## **5.18 Dictionaries**

Merupakan data yang satu sama lainnya berkaitan.

memahami dictionaries, kita akan melihat kembali phyton list

In [161]:
#LATIHAN 1
#akan menampilkan data saya 

#mengisi data saya yang terdiri dari nama, nim, instansi, fakultas, prodi, alamat tinggal dan alamat asal
data_saya = {
    'nama': 'Diska Audian Maharani',
    'nim' : 2208541036,
    'instansi': 'Universitas Udayana',
    'fakultas': 'MIPA',
    'prodi': 'Matematika',
    'alamat_tinggal':'gang Melati Jimbaran',
    'alamat_asal':'Situbondo Jawa Timur',
}


In [162]:
#menampilkan 'nama' pada data saya
#menggunakan perintah print untuk menampilkan
print (data_saya['nama'])

Diska Audian Maharani


In [163]:
print (data_saya['Nama'])
#ini error karena kata 'Nama' tidak sesuai dengan yang ada pada data_saya
#yang benar adalah 'nama' seperti yang telah ditunjukkan di atas

KeyError: ignored

In [164]:
#akan menampilkan data nama yang ada di data saya
print (data_saya.get('nama'))

Diska Audian Maharani


In [165]:
#akan menampilkan data nama yang ada di data saya
print (data_saya.get('Nama'))
#data nama yang ditampilkan tidak ada karena kata 'Nama' tidak sesuai dengan yang ada di data saya
#oleh karena itu dia menghasilkan none

None


In [166]:
#akan menampilkan tanggal lahir
print(data_saya.get('tanggal_lahir'))
#data tanggal lahir yang ditampilkan tidak ada karena tanggal lahir bukan merupakan elemen dari data saya
#sehingga dia menghasilkan none

None


In [167]:
#akan menampilkan tanggal lahir
print(data_saya.get('tanggal_lahir', '23-08-2003'))
#data tanggal lahir dapat ditampilkan karena telah ditambahkan tanggal lahir pada print di atas
#sehingga dia dapat ditampilkan

23-08-2003


In [168]:
#setelah menampilkan tanggal lahir, kita mencoba melihat data saya, apakah tetap atau berisi tanggal lahir

print (data_saya)
#ternyata, data saya tetap seperti di awal tanpa ada penambahan tanggal lahir
#karena pada tanggal lahir di atas hanya berfungsi menampilkan saja

{'nama': 'Diska Audian Maharani', 'nim': 2208541036, 'instansi': 'Universitas Udayana', 'fakultas': 'MIPA', 'prodi': 'Matematika', 'alamat_tinggal': 'gang Melati Jimbaran', 'alamat_asal': 'Situbondo Jawa Timur'}


In [169]:
#coba menambahkan nomor hp pada data_saya
data_saya['nomor_hp'] = '085432789654' 
print (data_saya['nomor_hp'])
#gunakan perintah print agar dapat menampilkan nomor hp

085432789654


In [170]:
#coba menambahkan nomor hp pada data_saya
data_saya['tanggal_lahir'] = '23-08-2003'
print (data_saya['tanggal_lahir'])
#gunakan perintah print agar dapat menampilkan tanggal lahir

23-08-2003


In [171]:
#saya mencoba menambahkan nomor hp dan tanggal lahir pada data_saya

print (data_saya)
#nomor hp dan tanggal lahir bisa ditambahkan di dalam list data_saya
#karena pada nomor hp dan tanggal lahir di atas berfungsi untuk menambah list dalam data_saya

{'nama': 'Diska Audian Maharani', 'nim': 2208541036, 'instansi': 'Universitas Udayana', 'fakultas': 'MIPA', 'prodi': 'Matematika', 'alamat_tinggal': 'gang Melati Jimbaran', 'alamat_asal': 'Situbondo Jawa Timur', 'nomor_hp': '085432789654', 'tanggal_lahir': '23-08-2003'}


In [174]:
#membuat program untuk merubah nim yang tadinya berupa angka menjadi sebutan bilangan tersebut.
#angka menjadi sebutan bilangannya sendiri
angka = {
    '0': 'nol',
    '1': 'satu',
    '2': 'dua',
    '3': 'tiga',
    '4': 'empat',
    '5': 'lima',
    '6': 'enam',
    '7': 'tujuh',
    '8': 'delapan',
    '9': 'sembilan'
}

#jangan lupa untuk menambahkan koma di akhir, karena kalau lupa maka akan eror

In [175]:
nim = input ('Masukkan nim anda ')      #berfungsi untuk menampilkan nilai nim anda
nim_angka = ' '                         #menampilkan nim dalam bentuk angka
for isi in nim:                         
  nim += angka.get(isi) + ' '           #menampilkan nim berupa angka dan sebutan billangannya
print(nim )                             #gunakan perintah print untuk menampilkan semuanya

Masukkan nim anda 2208541036
2208541036dua dua nol delapan lima empat satu nol tiga enam 


# **5.19 Fungsi Dalam Python**

Pada dasarnya, fungsi dibentuk untuk menghindari pengulangan pembuatan program secara manual.

Gunakan fungsi untuk mempermudah dan meringkas program yang kita buat.

In [176]:
#LATIHAN 1

#membuat perintah untuk penginputan nama depan,tengah dan belakang
def full_nama(nama_depan, nama_tengah, nama_belakang):
  print(f'Nama lengkap saya adalah {nama_depan} {nama_tengah} {nama_belakang}')
#menggunakan perintah print untuk menampilkan apa yang telah dibuat tadi

In [177]:
nama_depan = input ('Nama depan saya adalah ')         #menamampilkan pengisian untuk nama bagian depan
nama_tengah = input ('Nama tengah saya adalah ')       #menampilkan pengisian untuk nama bagian tengah
nama_belakang = input ('Nama belakang saya adalah ')   #menampilkan pengisian untuk nama bagian akhir
full_nama(nama_depan, nama_tengah, nama_belakang)      #menampilkan full nama secara otomatis tapa perlu kita masukin nama depan, tengah, akhir nya lagi

Nama depan saya adalah Diska
Nama tengah saya adalah Audian
Nama belakang saya adalah Maharani
Nama lengkap saya adalah Diska Audian Maharani


In [178]:
#LATIHAN 2
#tugas fungsi dalam phyton

Ada dua jenis fungsi pada python yaitu:

-Menjalankan perintah

-Menampilkan hasil perhitungan

In [179]:
def waktu_sampai(jarak, kecepatan):  #data yang dibutuhkan adalah data jarak dan kecepatannya
  waktu = jarak/kecepatan            #rumus waktu sampai yakni jarak dibagi kecepatan
  print(waktu)                       #menggunakan perintah print untuk menampilkan apa yang telah dibuat

In [180]:
def waktu_tempuh(jarak,kecepatan):   #untuk mencari waktu tempuh, data yang digunakan adalah data jarak dan kecepatan
  waktu = jarak/kecepatan            #rumus waktu tempuh yakni sama seperti waktu sampai
  return waktu                       #menggunakan perintah print untuk menampilkan apa yang telah dibuat

In [181]:
waktu_sampai (120,80)        #ini artinya, dapat diketahui bahwa jarak nya 120 dengan kecepatan 80
                             #dengan ini diperoleh 1.5 karena 120 dibagi 80

1.5


In [182]:
waktu_tempuh (120, 80)       #ini artinya, dapat diketahui bahwa jaraknya adalah 120 dengan kecepatan 80
                             #dengan ini diperoleh 1.5 karena 120 dibagi 80

1.5

In [183]:
a = waktu_sampai (120, 80)     #kita simbolkan bahwa a itu adalah waktu sampai
print (a)                      #gunakan print untuk menampilkan

1.5
None


In [184]:
b = waktu_tempuh (120, 80)     #kita simbolkan bahwa b itu adalah waktu tempuh
print (b)                      #gunakan print untuk menampilkan

1.5


berdasarkan fungsi di atas, dapat diberi kesimpulan bahwa waktu sampai = waktu tempuh. Karena 1.5=1.5

Jadi, fungsi pada python juga bisa menghitung waktu tempuh dan sampai seseorang.

In [185]:
import numpy as np

In [186]:
#mendeklarasikan fungsi

def luas_segitiga (alas, tinggi):    #jadi untuk menemukan luas dari segitiga, kita hanya perlu tau alas dan tingginya
    luas = (1/2)*alas*tinggi         #kita juga perlu memasukkan rumus pada python, karena secanggih apapun tetap tidak bisa membuat rumus dengan sendirinya tanpa arahan
    return luas


In [187]:
#mendeklarasikan fungsi
    
def luas_persegi_panjang (panjang, lebar):     #untuk menemukan luas persegi panjang, kita hanya perlu tau panjang dan lebarnya
  luas = panjang*lebar                         #masukkan rumus luas persegi panjang      
  return luas                        

In [188]:
#mendeklarasikan fungsi

def luas_persegi (sisi):        #untuk menemukan luas persegi, kita hanya perlu tau sisinya
  luas = sisi*sisi              #rumus luas persegi
  return luas

program di bawah ini dibuat dengan 3 bidang dan luas. Untuk menentukan bidang apa yang akan diinput, maka digunakan if, dan apabila bidang yang diinput tidak sesuai dengan bidang dan luas yang ada, maka akan langsung ke else

In [190]:
jenis_bidang = input ('jenis bidangnya: ')
if jenis_bidang.upper () == 'SEGITIGA':
  alas = float(input('berapakah panjang alasnya? '))
  tinggi = float(input('barapakah tingginya? '))
  luas = luas_segitiga(alas, tinggi)
  print(f'luas {jenis_bidang} adalah {luas}')
elif jenis_bidang.upper () == 'PERSEGI PANJANG':
  panjang = float(input('berapakah panjangnya? '))
  lebar = float(input('berapakah lebarnya? '))
  luas = luas_persegi_panjang(panjang, lebar)
  print(f'luas {jenis_bidang} adalah {luas}')
elif jenis_bidang.upper () == 'PERSEGI':
  sisi = float(input('berapakah panjang sisinya? '))
  luas = luas_persegi(sisi)
  print(f'luas {jenis_bidang} adalah {luas}')
else:
  print(f'bidang {jenis_bidang} yang anda masukkan tidak ada')
  print('pilihannya hanya SEGITIGA, PERSEGI PANJANG, PERSEGI')
  print('terima kasih')

jenis bidangnya: SEGITIGA
berapakah panjang alasnya? 6
barapakah tingginya? 12
luas SEGITIGA adalah 36.0


# **5.20 Numpy**

Merupakan salah satu Library dalam python yang memiliki keunggulan dalam perhitungan menggunakan vektor dan matrik dalam berbagai dimensi.

# 5.20.1 Perintah Dasar Pada Numpy

Akan dipaparkan mengenai beberapa perintah dalam numpy diantaranya adalah memanggil numpy, mengetahui dimensi dan ukuran variabel 

In [200]:
#Latihan soal di ppt

a = np.array ([0,1,2,3,4])   #ini merupakan vektor baris
print(a)                     #gunakan print untuk menampilkan yang dipaggil

[0 1 2 3 4]


In [191]:
b = np.array ([[5,6,7,8],[9,8,7,6],[2,3,4,7]])      #ini merupakan vektor baris
print(b)                                  #gunakan print untuk menampilkan b

[[5 6 7 8]
 [9 8 7 6]
 [2 3 4 7]]


In [195]:
c = np.array ([[[0,1,2,3], [4,5,6,7]],    #ini merupakan matrik 
              [[8,9,8,7], [6,5,4,3]], 
              [[1,2,3,4], [5,6,7,8]],
              [[2,3,4,5], [8,2,4,1]]])
print (c)                                 #gunakan print untuk menampilkan c
                                        

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [8 2 4 1]]]


In [ ]:
a.ndim
#menentukan banyaknya dimensi pada a

1

In [196]:
b.ndim
#memntukan banyaknya dimensi pada b

2

In [197]:
c.ndim
#menentukan banyaknya dimensi pada c

3

In [201]:
a.shape
#menampilkan 1 dimensi dan berukuran 5 

(5,)

In [199]:
b.shape
#menampilkan 3 dimensi dan ukurannya 4 

(3, 4)

In [202]:
c.shape
#menampilkan 4 dimensi berukuran dengan baris 2 dan kolom 4 pada c

(4, 2, 4)

Kesimpulannya:
ndim adalah untuk menampilkan dimensi pada matriks yang dituju.
shape adalah menampilkan atau menentukan 

# 5.20.2 Memanggil anggota, kolom dan baris dengan numpy

In [204]:
#LATIHAN 1

#menampilkan bilangan random
d = np.array([[2,3,4,5,6,7], [4,1,2,3,5,6],[7,8,4,2,1,3], [2,4,7,3,1,9]])
print(d)

[[2 3 4 5 6 7]
 [4 1 2 3 5 6]
 [7 8 4 2 1 3]
 [2 4 7 3 1 9]]


In [205]:
d[3,:]
#menampilkn semua baris ketiga tanpa kolom

array([2, 4, 7, 3, 1, 9])

In [206]:
d[:,3]
#menampilkan semua kolom ketiga tanpa kolom

array([5, 3, 2, 3])

In [ ]:
d[2,1]
#menampilkan baris ke 2 dengan kolom ke 1

8

In [ ]:
d[1,3]
#menampilkan baris ke 1 dengan kolom ke 3

3

In [ ]:
d[1,2:3]
#menampilkan data array dengan index ke 1, kolom 2 sampai 3 dan tidak termasuk kolom ke 3

array([2])

In [ ]:
d[0,1:2]
#menampilkan data array dengan index ke 0, kolom 1 sampai 2 dan tidak termasuk kolom ke 2

array([3])

In [ ]:
d[0,0] = 100
print(d)
#mengubah angka di kolom 0 dan baris 0 menjadi 100

[[100   3   4   5   6   7]
 [  4   1   2   3   5   6]
 [  7   8   4   2   1   3]
 [  2   4   7   3   1   9]]


# 5.20.3 Matriks pada numpy

Untuk membuat berbagai jenis matrik

In [ ]:
np.ones((10,5))
#menampilkan matrik 10*3 dengan elemen keseluruhan 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((3,5))
#menampilkan matriks 3*5 dengan elemen keseluruhan 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.identity(8)
#menampilkan matriksidentitas dengan 8*8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.ones ((5,6,7))
#menampilkan matriks 2 dimensi dengan 6*5 yang elemennya 1

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
    

In [ ]:
np.full ((2,1),3)
#menampilkan matriks 2*1 yang elemennya 3

array([[3],
       [3]])

In [ ]:
np.random.rand (2,5)
#menampilkan matriks 2*5

array([[0.89723327, 0.96441189, 0.50593098, 0.19662899, 0.86520955],
       [0.56965178, 0.95086619, 0.82981386, 0.70759287, 0.1470205 ]])

In [ ]:
np.random.randint(2, 5, size=(3,1)) #int
#menampilkan matriks 3*1 dengan int dari 2-5

array([[4],
       [2],
       [2]])

# 5.20.4 Copy Pada Numpy

Untuk menghindari perubahan variabel awal yang tidak dikehendaki, maka diperlukan perintah copy

In [220]:
#LATIHAN 1

a = np.array ([2,5,7,9,10])    #diambil bilangan random
print (a)                      #gunakan perintah print untuk menampilkan a

[ 2  5  7  9 10]


In [211]:
b = a+1       #semua elemen yang ada di a ditambah dengan 1
print(b)      #gunakan perintah print untuk menampilkan b

[ 3  6  8 10 11]


In [212]:
c=np.array([2,4,7,5,1])     #diambil bilangan random
print(c)                    #gunakan perintah print untuk menampilkan c

[2 4 7 5 1]


In [213]:
d =c.copy ()+1       #semua elemen yang ada di c ditambah dengan 1
print(d)             #gunakan perintah print untuk menampilkan d

[3 5 8 6 2]


In [214]:
print(c)           #dengan c tidak berubah nilai

[2 4 7 5 1]


In [221]:
c [0] = 50          #ini berarti mengubah indeks 1 dengan angka 50
print(c)

[50  4  7  5  1]


In [222]:
d [0] = 100       #mengubah nilai d di indeks 0 dengan angka 100
print(d)

[100   5   8   6   2]


In [223]:
print (a)

[ 2  5  7  9 10]


Kesimpulan: apabila data a tidak diubah ubah lagi, maka apabila dipanggil data a akan tetap sama seperti sebelumnya, berbeda apabila kita mengubah data a lagi, maka apabila dipanggil datanya akan muncul data a yang terakhir kali diubah

# 5.20.5 Operasi Matematika pada Numpy

In [ ]:
import numpy as np

In [232]:
#mendeskripsikan nilai array dari variabel pada numpy
a = np.array([1,3,6,4,8,9,10,12])
b = np.array([2,3,4,5,7,8,9,13,])
print(a)
print(b)
#menggunakan perintah print agar a dan b dapat ditampilkan

[ 1  3  6  4  8  9 10 12]
[ 2  3  4  5  7  8  9 13]


PENJUMLAHAN PADA ARRAY

In [233]:
#menggunakan operasi penjumlahan pada array

x1 = a+2     #nilai a saja yang ditambahkan 2
print(x1)


[ 3  5  8  6 10 11 12 14]


In [234]:
#menggunakan operasi penjumlahan pada array

x2 = b+2     #nilai b saja yang ditambahkan 2
print (x2)

[ 4  5  6  7  9 10 11 15]


In [236]:
#menggunakan operasi penjumlahan pada array

#nilai a dan b sama sama ditambahkan bilangan yang berbeda
x1 = a+5
x2 = b+3
print(x1)
print(x2)

[ 6  8 11  9 13 14 15 17]
[ 5  6  7  8 10 11 12 16]


PENGURANGAN PADA ARRAY

In [237]:
#menggunakan operasi pengurangan pada array

x3 = a-2     #nilai a saja yang dikurangi 2
print(x3)

[-1  1  4  2  6  7  8 10]


In [239]:
#menggunakan operasi pengurangan pada array

x4 = b-2      #nilai b saja yang dikurangi 2
print(x4)

[ 0  1  2  3  5  6  7 11]


In [241]:
#menggunakan pengurangan pada array

#menampilkan pengurangan yang dihasilkan dari a dan b apabila dikurangi oleh bilngan yang berbeda
x3 = a-3
x4 = b-4
print(x3)
print(x4)

[-2  0  3  1  5  6  7  9]
[-2 -1  0  1  3  4  5  9]


PERKALIAN PADA ARRAY

In [242]:
#menggunakan perkalian pada array

x5 = a*2     #nilai a saja yang dikalikan 2
print(x5)

[ 2  6 12  8 16 18 20 24]


In [243]:
#menggunakan perkalian pada array

x6 = b*3     #nilai b saja yang dikalikan 3
print(x6)

[ 6  9 12 15 21 24 27 39]


PEMBAGIAN PADA ARRAY

In [245]:
#menggunakan pembagian pada array

x7 = a/2
x8 = b/2
print (x7)
print (x8)

[0.5 1.5 3.  2.  4.  4.5 5.  6. ]
[1.  1.5 2.  2.5 3.5 4.  4.5 6.5]


PEMANGKATAN PADA ARRAY

In [246]:
#menggunakan pemangkatan pada array

x9 = a**2
x10 = b**3
print (x9)
print (x10)
#kedua a dan b dipangkatkan masing-masing dengan angka yang berbeda

[  1   9  36  16  64  81 100 144]
[   8   27   64  125  343  512  729 2197]


TRIGONOMETRI PADA NUMPY

In [247]:
#menggunakan cosinus pada array
x4 = np.cos(a)      #nilai a saja 
print(x4)

[ 0.54030231 -0.9899925   0.96017029 -0.65364362 -0.14550003 -0.91113026
 -0.83907153  0.84385396]


In [248]:
#menggunakan sinus pada array
x5 = np.sin(a)
print(x5)

[ 0.84147098  0.14112001 -0.2794155  -0.7568025   0.98935825  0.41211849
 -0.54402111 -0.53657292]


KUADRAT PADA NUMPY

In [250]:
#meghitung nilai dari akar kuadrat
x6 = np.sqrt(a)
print(x6)

[1.         1.73205081 2.44948974 2.         2.82842712 3.
 3.16227766 3.46410162]


# 5.20.6 Perkalian pada matrik pada numpy

In [251]:
#LATIHAN

#menampilan perkalian pada matrik pada numpy  
a = np.array([[[2,4,6,], [7,8,9], [10,13,15]]])  #memggunakan angka random
print(a)
#gunakan print untuk menampilkan a

[[[ 2  4  6]
  [ 7  8  9]
  [10 13 15]]]


In [252]:
b= np.array([[[6,7,8], [7,8,10], [13,15,12]]]) #menggunakan angka random
print(b)
#gunakan print untuk menampilkan b

[[[ 6  7  8]
  [ 7  8 10]
  [13 15 12]]]


In [253]:
c=a*b      #matriks a dikali matriks b hasilnya sama dengan c
print(c)   #gunakan print untuk menampilkan c

[[[ 12  28  48]
  [ 49  64  90]
  [130 195 180]]]


In [254]:
e=np.array([[12,13],[14,16], [6,7], [8,9]]) #mendeksripsikan data array
print(e)

[[12 13]
 [14 16]
 [ 6  7]
 [ 8  9]]


In [255]:
f=np.matmul(a,e)       #error tidak tahu kenapa pak
print(f)

ValueError: ignored

# 5.20.7 min,max dan sum pada numpy

Ini berfungsi untuk mengetahui nilai terkecil dan terbesar dari suatu data

In [256]:
a = np.array([[4,5,6,7,8],  #mendeskripsikan elemen pada variabel a yang berupa data array
             [1,2,3,4,5],
             [4,5,6,7,8]])
print(a)

[[4 5 6 7 8]
 [1 2 3 4 5]
 [4 5 6 7 8]]


MENAMPILKAN NILAI MINIMUM

In [257]:
b= np.min(a) #nilai minimal dari data array a
print(b)     #gunakan print agar b dapat terbaca

1


In [262]:
c= np.min (a, axis = 0)  #nilai minimal dari kolom a
print (c)                #gunakan print agar c terbaca

[1 2 3 4 5]


In [263]:
d=np.min (a, axis = 1) #menampilkan nilai minimum dari baris a
print (d)              #gunakan print agar d terbaca

[4 1 4]


MENAMPILKAN NILAI MAKSIMUM

In [265]:
e= np.max(a)   #nilai maksimal dari data nilai a
print(e)       #gunakan print agar c terbaca

8


In [266]:
f= np.max (a, axis = 0)  #menampilkan nilai maksimum pada kolom
print (f)

[4 5 6 7 8]


In [268]:
g= np.max (a, axis = 1)  #menampilkan nilai maksimum pada baris
print (g)

[8 5 8]


MENAMPILKAN SUM


In [269]:
p= np.sum(a)   #nilai penjumlahan dari matriks a
print(p)

75


In [270]:
q= np.sum(a, axis = 0)  #nilai penjumlahan pada kolom a
print(q)

[ 9 12 15 18 21]


In [271]:
r= np.sum(a, axis = 1)   #nilai penjumlahan pada baris a
print (r)

[30 15 30]


# **TERIMA KASIH**